theme: jekyll-theme-minimal
title: dac - Diagrams as Code
description: All-in-one diagram-as-code playground. Python diagrams, PlantUML, Mermaid, Graphviz & D2 in one Docker container.
show_downloads: true
